prefix = "C-g"

[bindings]
new-tab = ["t", "c"]
split-right = ["v", "%"]
split-below = ["h", "\""]
attach = ["a"]
rename-tab = ["r"]
tab-options = ["m"]
next-tab = ["n"]
previous-tab = ["p"]
next-pane = ["o"]
previous-pane = ["O"]
focus = ["z"]
workspaces = ["w"]
workspace-options = ["M"]
new-workspace = ["W"]
rename-workspace = ["R"]
next-workspace = ["]"]
previous-workspace = ["["]
close-pane = ["x"]
close-tab = ["&"]
copy-selection = ["y"]
sidebar = ["s"]
refresh-viewer = ["f"]
quit = ["d"]
select-tab-1 = []
select-tab-2 = []
select-tab-3 = []
select-tab-4 = []
select-tab-5 = []
select-tab-6 = []
select-tab-7 = []
select-tab-8 = []
select-tab-9 = []
select-workspace-1 = []
select-workspace-2 = []
select-workspace-3 = []
select-workspace-4 = []
select-workspace-5 = []
select-workspace-6 = []
select-workspace-7 = []
select-workspace-8 = []
select-workspace-9 = []

[direct]
new-tab = ["super+t"]
split-right = ["super+d"]
split-below = ["super+shift+d"]
attach = ["super+shift+a"]
rename-tab = ["super+r"]
tab-options = []
next-tab = ["super+shift+bracket_right"]
previous-tab = ["super+shift+bracket_left"]
next-pane = ["super+bracket_right"]
previous-pane = ["super+bracket_left"]
focus = ["super+shift+enter"]
workspaces = []
workspace-options = []
new-workspace = ["super+shift+n"]
rename-workspace = ["super+shift+r"]
next-workspace = ["super+alt+right"]
previous-workspace = ["super+alt+left"]
close-pane = ["super+w"]
close-tab = ["super+shift+w"]
copy-selection = ["super+c"]
sidebar = ["super+b"]
refresh-viewer = []
quit = []
select-tab-1 = ["super+1"]
select-tab-2 = ["super+2"]
select-tab-3 = ["super+3"]
select-tab-4 = ["super+4"]
select-tab-5 = ["super+5"]
select-tab-6 = ["super+6"]
select-tab-7 = ["super+7"]
select-tab-8 = ["super+8"]
select-tab-9 = ["super+9"]
select-workspace-1 = ["super+alt+1"]
select-workspace-2 = ["super+alt+2"]
select-workspace-3 = ["super+alt+3"]
select-workspace-4 = ["super+alt+4"]
select-workspace-5 = ["super+alt+5"]
select-workspace-6 = ["super+alt+6"]
select-workspace-7 = ["super+alt+7"]
select-workspace-8 = ["super+alt+8"]
select-workspace-9 = ["super+alt+9"]
